# Site settings
baseurl = "http://herbsusmann.com"
languageCode = "en-us"
title = "Herb Susmann"
theme = "cactus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Herb Susmann"
	description = "Describe your website"
	bio = "Blogger - Programmer - Gopher"
	# Enter optionally your twitter account
	twitter = "herbps10"
	enableRSS = true

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm an enthusiastic gopher."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

    # Social icons style - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/herbps10"
    github   = "https://www.github.com/herbps10"
